name: afriha_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.2.0  # Replace with the appropriate version of the logging package
  #google_fonts: ^6.2.0
  omni_datetime_picker: ^1.0.9
  location_picker_flutter_map: ^3.0.1
  chat_bubbles: ^1.6.0
  http: ^1.2.0
  flutter_spinkit: ^5.2.1
  provider: ^5.0.0
  file_picker: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons: 
    android: true
    image_path: "Images/LOGO.png"

flutter:
  uses-material-design: true

  assets:
  - Images/

  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/Nunito.ttf
    
    - family: Calistoga
      fonts:
        - asset: fonts/Calistoga.ttf
        
