# Generated by Django 5.0.4 on 2024-04-23 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('existences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domaine',
            name='photo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
