# Generated by Django 5.0.4 on 2024-04-28 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('existences', '0003_remove_commentaires_notation_alter_artisan_notation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demande',
            name='highlighted',
        ),
        migrations.AddField(
            model_name='demande',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='demande',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='demande',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='existences.client'),
        ),
    ]
