# Generated by Django 5.0.4 on 2024-04-28 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('existences', '0004_remove_demande_highlighted_demande_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='existences.client'),
        ),
    ]
