# Generated by Django 5.0.4 on 2024-04-28 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('existences', '0005_alter_demande_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='owner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='existences.client'),
            preserve_default=False,
        ),
    ]
