# Generated by Django 5.0.2 on 2024-04-28 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('existences', '0007_remove_demande_owner_demande_client_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demande',
            name='client_id',
        ),
        migrations.AddField(
            model_name='demande',
            name='client',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='existences.client'),
            preserve_default=False,
        ),
    ]
