# Generated by Django 5.0.4 on 2024-04-30 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('existences', '0009_remove_client_client_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artisan',
            name='domaine_expertise',
        ),
        migrations.AddField(
            model_name='artisan',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='artisan',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='commune',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='nb_interventions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='notation',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='wilaya',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
