# Generated by Django 5.0.4 on 2024-05-01 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('existences', '0010_remove_artisan_domaine_expertise_artisan_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artisan',
            name='artisan_id',
        ),
    ]
