# Generated by Django 5.0.4 on 2024-05-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('existences', '0011_remove_artisan_artisan_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rendezvous',
            name='Confirme',
        ),
        migrations.AddField(
            model_name='demande',
            name='Confirme',
            field=models.BooleanField(default=False),
        ),
    ]
