# Generated by Django 5.0.4 on 2024-05-02 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('existences', '0013_demande_artisan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demandeacceptee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artisan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='existences.artisan')),
                ('demande_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='existences.demande')),
            ],
        ),
    ]
