# Generated by Django 5.0.4 on 2024-05-06 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('existences', '0014_demandeacceptee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentaires',
            name='client',
        ),
        migrations.RemoveField(
            model_name='commentaires',
            name='creer',
        ),
        migrations.AddField(
            model_name='commentaires',
            name='notation',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='demande',
            name='notee',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='notation',
            field=models.FloatField(default=4),
        ),
    ]
