# Generated by Django 5.0.4 on 2024-05-06 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('existences', '0015_remove_commentaires_client_remove_commentaires_creer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaires',
            name='notation',
            field=models.FloatField(null=True),
        ),
    ]
