# Generated by Django 5.0.4 on 2024-05-11 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('existences', '0017_alter_message_options_remove_message_dialogue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisan',
            name='confirmer',
            field=models.BooleanField(default=False),
        ),
    ]
