# Generated by Django 5.0.4 on 2024-05-12 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('existences', '0019_notification_receiver_alter_notification_date_envoie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artisan',
            name='commune',
        ),
        migrations.RemoveField(
            model_name='artisan',
            name='wilaya',
        ),
        migrations.RemoveField(
            model_name='client',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='client',
            name='commune',
        ),
        migrations.RemoveField(
            model_name='client',
            name='wilaya',
        ),
    ]
